name: Append to release

on:
  release:
    types:
      - "published"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: flutterwebtools-linux
          - os: macOS-latest
            output-name: flutterwebtools-mac
          - os: windows-latest
            output-name: flutterwebtools-windows.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: setup dart
        uses: DanTup/gh-actions/setup-dart@master
      - name: create build dir
        run: mkdir build
      - run: dart pub get
      - name: build
        run: dart2native bin/main.dart -v -o build/${{ matrix.output-name }}
      - name: upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ matrix.output-name }}
          asset_name: ${{ matrix.output-name }}
          tag: ${{ github.ref }}
          overwrite: true
