name: Tests

on:
  push:
  schedule: # execute every week
    - cron: "1 0 * * 1"

jobs:
  dart_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: DanTup/gh-actions/setup-dart@master
      - run: dart pub get
      - run: dart test
